#version: '3.9'

services:
  db:
    image: postgres:15
    container_name: youtube_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youtube_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    container_name: youtube_etl
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: youtube_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
    command: python src/run_etl.py

  streamlit:
    build: .
    container_name: youtube_streamlit
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: youtube_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
    command: >
      streamlit run src/YouTube_dashboard.py
      --server.port=8501
      --server.address=0.0.0.0

volumes:
  postgres_data:
